[features]
seeds = false
[programs.localnet]
grape_collection_state = "8Dk32gShk85fpj2xDC99p3svCrWDuJf8tQ9JWWfddev3"

[programs.devnet]
grape_collection_state = "8Dk32gShk85fpj2xDC99p3svCrWDuJf8tQ9JWWfddev3"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/fzzyyti/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
