[features]
seeds = false
[programs.localnet]
grape_collection_state = "DxMn9z9sD9n9fdrvgfa9fuBngYcQXfcofGp2KRZwA7wj"

[programs.devnet]
grape_collection_state = "DxMn9z9sD9n9fdrvgfa9fuBngYcQXfcofGp2KRZwA7wj"


[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kirk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
